# Generated by Django 6.0.2 on 2026-03-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finishedclient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('packet', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
